### ISSUE TITLE
How to Load different models?

### ISSUE THREAD

**Issue by CypherpunkSamurai** [rapidrabbit76/stable-diffusion-API#3]
# Describe of bug
I want to load different model

**Comment by rapidrabbit76** [comment]
@CypherpunkSamurai 

well, hello there 

# from code 
if you use main,develop branche and 1.0.0 tag, change the [MODEL_ID](https://github.com/rapidrabbit76/stable-diffusion-API/blob/9a5a4132808557fd70be25db48972c5f7b2ab31f/core/settings/settings.py#L8) env, the MODEL_ID is huggingface repo id 

sample is [sd-1-5](https://huggingface.co/runwayml/stable-diffusion-v1-5)

```python
class ModelSetting(BaseSettings):
    MODEL_ID: str = "runwayml/stable-diffusion-v1-5"
```

# docker-compose 

if you want using docker-compose insert MODEL_ID environment 

```yaml
    environment:
      MODEL_ID: runwayml/stable-diffusion-v1-5
```

**Comment by CypherpunkSamurai** [comment]
Can I load `.cpkt` models?

The duffusers models are limited in number as of now, is there any chance I load a `.cpkt` and vae?

**Comment by rapidrabbit76** [comment]
@CypherpunkSamurai 

yes you can use `.ckpt` models. personally, I use it 
however, it cannot be used directly.
you need to convert `.ckpt` to `diffusers` format.



follow this steps

# 1. convert `.ckpt` models to `diffusers` formt
- check [this script](https://github.com/huggingface/diffusers/blob/main/scripts/convert_original_stable_diffusion_to_diffusers.py)


# 2. load each components in pipeline 
- check this code  
```python

@lru_cache(maxsize=1)
def build_vae() -> AutoencoderKL:
    device = env.CUDA_DEVICE
    logger.info("stable diffusion model VAE loading...")
    vae = AutoencoderKL.from_pretrained(
        env.MODEL_PATH,
        subfolder="vae",
        revision="fp16",
        torch_dtype=torch.float16,
    )
    vae = vae.to(device)
    return vae


@lru_cache(maxsize=1)
def build_unet():
    device = env.CUDA_DEVICE

    logger.info("stable diffusion model Unet loading...")
    unet = UNet2DConditionModel.from_pretrained(
        env.MODEL_PATH,
        subfolder="unet",
        revision="fp16",
        torch_dtype=torch.float16,
    )
    unet = unet.to(device)
    return unet


@lru_cache(maxsize=1)
def build_tokenizer():
    logger.info("stable diffusion model tokenizer loading...")
    tokenizer = CLIPTokenizer.from_pretrained(
        env.MODEL_PATH,
        subfolder="tokenizer",
    )
    return tokenizer


@lru_cache(maxsize=1)
def build_text_encoder():
    device = env.CUDA_DEVICE

    logger.info("stable diffusion model text encoder loading...")
    text_encoder = CLIPTextModel.from_pretrained(
        os.path.join(env.MODEL_PATH, "text_encoder")
    )
    text_encoder = text_encoder.to(device)
    return text_encoder
```

in this case You need MODEL_PATH (path of converted `.ckpt` model) var in Settings


I hope this helps.

**Comment by CypherpunkSamurai** [comment]
I actually wanted to use it with multiple models that are in `.ckpt` format, also the many new models available are being released in `.ckpt` format. 

I hope you add support for it later. Thanks for now :)

**Comment by rapidrabbit76** [comment]
@CypherpunkSamurai 

OK, I understood what you meant. 
Consider supporting load the original ckpt directly.
thx!

**Comment by rapidrabbit76** [comment]
@CypherpunkSamurai 

check new main or develop branch 

ckpt file was supported by converting.

if work, close this issues
