### ISSUE TITLE
Generate images simultaneously

### ISSUE THREAD

**Issue by willydavid1** [rapidrabbit76/stable-diffusion-API#7]
Is it possible to generate images at the same time? Currently it works with two requests at the same time, but is it possible to generate two images simultaneously without waiting for a queue?

**Comment by rapidrabbit76** [comment]
@willydavid1 

operations cannot be done simultaneously(concurrently, at the same time) because they require the use of the GPU.

You can use the method of "launching multiple servers" and "load balancing".
I am solving this problem like that.

**Comment by willydavid1** [comment]
Ok, would it be other instances (cpu and gpu) to generate images and not queue the generations in a single instance?

Looks good thanks! I'll check it out.
