### ISSUE TITLE
Facing Connection Error While Running API 

### ISSUE THREAD

**Issue by ParameshwarM** [rapidrabbit76/stable-diffusion-API#8]
I've followed these steps and running from my personal system 

RUN from code (frontend)
1. install python Requirements
pip install \
    streamlit==1.12.2 \
    requests==2.27.1 \
    requests-toolbelt==0.9.1 \
    pydantic==1.8.2 \
    streamlit-drawable-canvas==0.9.2
2. RUN streamlit frontend
streamlit run inpaint.py

But im getting below error 

ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /%5Cinpaint (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001A5C72EEA70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

![Screenshot (74)](https://user-images.githubusercontent.com/36466883/227552944-33511475-338b-4f4c-b717-ecacc19fcdb1.png)

**Comment by rapidrabbit76** [comment]
hi, @ParameshwarM 

sorry for the late reply.

when I checked the error, it seems that the backend is not active.
did you run the backend process?
the repo is divided into backend and frontend.

**Comment by ParameshwarM** [comment]
i did run the backend process too let me check once again
